name: elkitap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #==================== FIREBASE ====================#
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^15.0.0
  firebase_performance: ^0.10.1+10
  flutter_local_notifications: ^18.0.1

  #==================== STATE MANAGEMENT ====================#
  get: ^4.6.6

  #==================== NETWORK ====================#
  http:
  dio: ^5.3.3

  #==================== UI & UX ====================#
  lottie: ^3.3.0
  flutter_svg: ^2.0.12
  pinput: ^5.0.1
  shimmer: ^3.0.0
  iconly: ^1.0.1

  #==================== MEDIA & PLAYER ====================#
  just_audio: ^0.10.5
  cached_network_image: ^3.3.1

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  #==================== UTILITIES ====================#
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  crypto: ^3.0.7
  encrypt: ^5.0.3
  share_plus: ^11.0.0
  app_links: ^6.3.2
  connectivity_plus: ^6.1.3
  webview_flutter: ^4.5.0
  upgrader: ^11.5.0
  restart_app: ^1.3.2
  ntp: ^2.0.0
  qr_code_scanner_plus: ^2.0.11
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^9.0.0
  archive: ^3.4.0

  #==================== DEVICE & HARDWARE ====================#
  flutter_blue_plus: ^2.0.2
  mobile_scanner: ^6.0.0

  #==================== EPUB READER ====================#
  cosmos_epub:
    path: ./packages/elkitap_epub
  epubx: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/splash.json

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
 
